name: Camelia
description: Draw.
main: eu.carrade.amaury.Camelia.Camelia
version: 1.0
author: "Amaury Carrade"

depend:
  - SamaGamesAPI

commands:
  mot:
    description: Permet de proposer un mot.
    usage: /mot <mot>
  word:
    description: Permet de proposer un mot.
    usage: /word <mot>