name: Camelia
description: Draw.
main: eu.carrade.amaury.Camelia.Camelia
version: 1.0
author: "Amaury Carrade"

depend:
  - SamaGamesAPI

commands:
  mot:
    description: Permet de proposer un mot.
    usage: /mot <mot>
    aliases:
      - word

  indice:
    description: Permet de changer l'endroit où est affiché l'indice
    usage: /<command>

  hint:
    description: Invoque un indice
    usage: /<command>
