name: Camelia
description: Draw.
main: eu.carrade.amaury.Camelia.Camelia
version: 1.0
author: "Amaury Carrade"

depend:
  - SamaGamesAPI

commands:
  mot:
    description: Permet de proposer un mot.
    usage: /mot <mot>
    aliases:
      - word

  options:
    description: "Permet de changer les options de jeu du joueur : position de l'indice, difficulté, sons..."
    usage: /<command>

  hint:
    description: Invoque un indice
    usage: /<command>
